# Generated by Django 2.2 on 2020-05-25 17:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('archivo', models.FileField(upload_to='ejercicios/')),
                ('is_active', models.BooleanField(default=False)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clases.Unidad')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, max_length=1000, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Alumno')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ejercicios.Ejercicio')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Alumno')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ejercicios.Ejercicio')),
            ],
            options={
                'verbose_name': 'Intento',
                'verbose_name_plural': 'Intentos',
            },
        ),
        migrations.CreateModel(
            name='CalificacionEjercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Alumno')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ejercicios.Ejercicio')),
            ],
        ),
    ]
